var starting_page = document.querySelector(".starting_page"),
  reward_choice = document.querySelectorAll(".reward_choice"),
  reward_emoji = document.querySelector(".reward_emoji"),
  point_emoji = document.querySelector(".point_emoji"),
  choice_btn = document.querySelectorAll(".choice"),
  choice1 = document.querySelector("#choice1"),
  choice2 = document.querySelector("#choice2"),
  right_choice = document.querySelector("#right_choice"),
  modal_wrapper = document.querySelector(".modal_wrapper"),
  modal = document.querySelector(".modal"),
  point = document.querySelector(".point"),
  score_points = document.querySelector(".score_num"),
  progress = document.querySelector(".progress"),
  hint_button = document.querySelector(".hint_button"),
  fst_ltr = document.querySelector(".fst_ltr"),
  lst_ltr = document.querySelector(".lst_ltr"),
  modal_emoji = document.querySelector(".modal_emoji"),
  play_btn = document.querySelector(".play_again"),
  reset_btn = document.querySelector(".reset"),
  check = document.querySelector(".check"),
  emoji = document.querySelector(".emoji"),
  answer = document.querySelector(".answer"),
  celebration_emojis = [
    "&#128170;",
    "&#128525;",
    "&#128526;",
    "&#128571;",
    "&#129321;",
    "&#128079;",
    "&#127881;",
    "&#127882;",
    "&#129470;",
  ],
  emojis_list = {
    "Monkey":"&#128018;",
    "Gorilla":"&#129421;",
    "Dog":"&#128021;",
    "Poodle":"&#128041;",
    "Wolf":"&#128058;",
    "Fox":"&#129418;",
    "Raccoon":"&#129437;",
    "Cat":"&#128049;",
    "Lion":"&#129409;",
    "Tiger":"&#128047;",
    "Leopard":"&#128006;",
    "Horse":"&#128014;",
    "Unicorn":"&#129412;",
    "Zebra":"&#129427;",
    "Deer":"&#129420;",
    "Cow":"&#128046;",
    "Bull":"&#128002;",
    "Buffalo":"&#128003;",
    "Cow":"&#128004;",
    "Pig":"&#128022;",
    "Boar":"&#128023;",
    "Ram":"&#128015;",
    "Sheep":"&#128017;",
    "Goat":"&#128016;",
    "Camel":"&#128042;",
    "Lama":"&#129433;",
    "Giraffe":"&#129426;",
    "Elephant":"&#128024;",
    "Rhinoceros":"&#129423;",
    "Hippopotamus":"&#129435;",
    "Mouse":"&#128045;",
    "Rat":"&#128000;",
    "Hamster":"&#128057;",
    "Rabbit":"&#128007;",
    "Chipmunk":"&#128063;",
    "Hedgehog":"&#129428;",
    "Bat":"&#129415;",
    "Bear":"&#128059;",
    "Koala":"&#128040;",
    "Panda":"&#128060;",
    "Kangaroo":"&#129432;",
    "Badger":"&#129441;",
    "Turkey":"&#129411;",
    "Chicken":"&#128020;",
    "Rooster":"&#128019;",
    "Chick":"&#128037;",
    "Bird":"&#128038;",
    "Penguin":"&#128039;",
    "Dove":"&#128330;",
    "Eagle":"&#129413;",
    "Duck":"&#129414;",
    "Swan":"&#129442;",
    "Owl":"&#129417;",
    "Peacock":"&#129434;",
    "Parrot":"&#129436;",
    "Frog":"&#128056;",
    "Crocodile":"&#128010;",
    "Turtle":"&#128034;",
    "Lizard":"&#129422;",
    "Snake":"&#128013;",
    "Sauropod":"&#129429;",
    "T-Rex":"&#129430;",
    "Whale":"&#128011;",
    "Dolphin":"&#128044;",
    "Fish":"&#128031;",
    "Blowfish":"&#128033;",
    "Shark":"&#129416;",
    "Octopus":"&#128025;",
    "Seashell":"&#128026;",
    "Snail":"&#128012;",
    "Butterfly":"&#129419;",
    "Worm":"&#128027;",
    "Ant":"&#128028;",
    "Honeybee":"&#128029;",
    "Lady Beetle":"&#128030;",
    "Cricket":"&#129431;",
    "Spider":"&#128375;",
    "Scorpion":"&#129410;",
    "Mosquito":"&#129439;",
    "Monkey":"&#128018;",
    "Gorilla":"&#129421;",
    "Dog":"&#128054;",
    "Poodle":"&#128041;",
    "Wolf":"&#128058;",
    "Fox":"&#129418;"
  },
  rwrd_emoji = reward_choice.innerText,
  rand_emoji =
    celebration_emojis[Math.floor(Math.random() * celebration_emojis.length)],
  obj = Object.entries(emojis_list),
  rand_obj = obj.sort(() => 0.5 - Math.random()),
  choices_order = ["1", "2", "3"],
  rand_choices_order = choices_order.sort(() => 0.5 - Math.random()),
  correct_sound = new Audio("sounds/correct-answer.mp3"),
  wrong_sound = new Audio("sounds/negative_beeps.mp3"),
  choose_reward_sound = new Audio("sounds/decide.mp3"),
  congrats_sound = new Audio("sounds/success.mp3");
for (var [key, value] of (Number(sessionStorage.getItem("point")) > 0 &&
  (starting_page.style.display = "none"),
reward_choice.forEach((a) => {
  a.addEventListener("click", () => {
    sessionStorage.setItem("reward_emoji", a.innerText),
      (reward_emoji.innerHTML = sessionStorage.getItem("reward_emoji")),
      (point_emoji.innerHTML = sessionStorage.getItem("reward_emoji")),
      choose_reward_sound.play(),
      (starting_page.style.transform = "translate(50%,-50%) scale(0)");
  });
}),
(reward_emoji.innerHTML = sessionStorage.getItem("reward_emoji")),
(point_emoji.innerHTML = sessionStorage.getItem("reward_emoji")),
Object.entries(rand_obj)))
  (emoji.innerHTML = value[1]),
    (right_choice.innerText = value[0]),
    (fst_ltr.innerText = value[0].charAt(0));
function choice_1_2() {
  for (var a of Object.values(obj).sort(() => 0.5 - Math.random()))
    choice1.innerText = a[0];
  for (var a of Object.values(obj).sort(() => 0.5 - Math.random()))
    choice2.innerText = a[0];
}
(right_choice.style.order = rand_choices_order[0]),
  (choice1.style.order = rand_choices_order[1]),
  (choice2.style.order = rand_choices_order[2]),
  (score_points.innerText = sessionStorage.getItem("point")),
  progress.setAttribute("value", sessionStorage.getItem("point")),
  choice_btn.forEach((a) => {
    a.addEventListener("click", () => {
      if (a.innerText == value[0]) {
        var b = Number(sessionStorage.getItem("point"));
        sessionStorage.setItem("point", ++b),
          (a.style.backgroundColor = "#52ff9d"),
          (a.innerText = `${value[0]}  ✓`),
          "80" == score_points.innerText
            ? ((answer.innerText = "CONGRATULATIONS \n you've Won The Game"),
              (modal.style.background =
                "repeating-radial-gradient(circle at 50% 31% ,#fde3b3,#fdf5e5 20%)"),
              (modal.style.outline = "10px solid #ecb57a"),
              (play_btn.style.display = "none"),
              (modal_wrapper.style.transform = "translate(50%,-50%) scale(1)"),
              (modal_wrapper.style.background =
                "linear-gradient(45deg,#b88bd1,#f8dea9)"),
              (modal_emoji.innerHTML = "&#127942;"),
              (reset_btn.style.backgroundColor = "#ffa828"),
              (reset_btn.style.color = "#ffffff"),
              congrats_sound.play())
            : ((point.style.display = "block"),
              (play_btn.innerText = "Continue \u25BA"),
              (answer.innerText = "Hooray, Good Answer"),
              (modal_wrapper.style.transform = "translate(50%,-50%) scale(1)"),
              (modal_emoji.innerHTML = rand_emoji),
              correct_sound.play()),
          play_btn.addEventListener("click", () => {
            location.reload();
          }),
          reset_btn.addEventListener("click", () => {
            sessionStorage.clear(), location.reload();
          });
      } else
        (a.style.backgroundColor = "#fe3a3a"),
          (a.style.color = "#ffffff"),
          (a.style.textDecoration = "line-through"),
          (answer.innerText = "Wrong Answer Kiddo"),
          (modal_wrapper.style.transform = "translate(50%,-50%) scale(1)"),
          (modal_emoji.innerHTML = "&#128575;"),
          wrong_sound.play(),
          play_btn.addEventListener("click", () => {
            (modal_wrapper.style.transform = "translate(50%,-50%) scale(0)"),
              (hint_button.style.display = "block");
          }),
          reset_btn.addEventListener("click", () => {
            sessionStorage.clear(), location.reload();
          });
    });
  }),
  window.addEventListener("DOMContentLoaded", choice_1_2());
